### PR TITLE
Easy made simple )))

### PR DESCRIPTION
**Pull request by yevhen**
Processing tasks one-by-one - why so complicated? :sunglasses:

What's wrong with old good warm and fuzzy `foreach` statement? It looks like you're trying to shoehorn `await` to LINQ query comprehension syntax (which does not support `await`). Why not just drop it?

I like when things are kept idiomatic and with `TaskEx` you just creating an additional DSL and for no particular reason. That's how it looks on a surface. :confused:

Maybe you need to augment the sample name? It doesn't show any pattern, actually. It just shows that LINQ query syntax is a piece of crap :grinning:

P.S. Also did some cleanup. I have R# installed :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
The whole poine of process one by one is to start all the operation but process them one by one. In your case (with `foreach` statement) you're starting and then processing them one by one. The result is significantly different!

**Comment by yevhen** [comment]
> This code is semantically not equivalent with previous one;) For instance, in my case I can start all the tasks simultaneously AND process the result as it come by. In your case you're starting new operation only when the previous one finishes.

Unless you change your code to run the tasks in parallel - my code is doing exactly the same ;)

That's why I've suggested you to change the name of the sample or change the code itself. Also, if you run tasks in parallel the name of the sample would be even more misleading. One-by-one is semantically means `sequential` which is not the case with parallel tasks.

What is actually happening is that you're processing results as soon as task completes, not one-by-one :)

**Comment by SergeyTeplyakov** [comment]
> Unless you change your code to run the tasks in parallel - my code is doing exactly the same ;)

You can try to run the code and you'll see that the result is different. I'm eagerly starting all the async operations by calling ToList on query expression. So they DO run in parallel:)

> One-by-one is semantically means sequential which is not the case with parallel tasks.

Name of this pattern was borrowed from the Pluralsight cource on async and parallel programming. The original name was wait tasks one-by-one. And I don't think it is misleading, because the name suggests that this code should "process" tasks results one by one, and that is exactly what is happening.

> What is actually happening is that you're processing results as soon as task completes, not one-by-one :)

Yep, tha is exactly what is happening, results are processed sequentially (i.e. one by one) as soon as they become awailable from multiple hot tassks.

So if you have better name for this idiom, I would glad to change the name.

**Comment by SergeyTeplyakov** [comment]
Ok, I've found a way how to compbine both worlds:

``` c#
/// <summary>
/// Method that transforms sequence of tasks into another sequence of tasks with strict
/// completion order. I.e. first item in the resulting sequence would be finished first,
/// second item - second etc. 
/// </summary>
/// <remarks>
/// This method helps to analyze the results not based on the order of the tasks in
/// the original sequence but in the order of completion.
/// </remarks>
public static IEnumerable<Task<T>> ProcessOneByOne<T>(IEnumerable<Task<T>> taskSequence)
{
    // Need to return task immediately, but it should be in complete state when the first task would be completed!
    Contract.Requires(taskSequence != null);

    var tasks = taskSequence.ToList();

    while (tasks.Count != 0)
    {
        // We whould have additional closure for each iteration but in a task-based word
        // this should be fine!

        var tcs = new TaskCompletionSource<T>();

        // Getting the first finished task
        Task.WhenAny(tasks).ContinueWith((Task<Task<T>> tsk) =>
        {
            tasks.Remove(tsk.Result);

            tcs.FromTask(tsk.Result);
        });

        yield return tcs.Task;
    }
}
```

Now, decorating original sequence of tasks with this method you would be able to use your foreach + await and get the same result that I would have in my original implementation.

P.S. I've ommited `tcs.FromTask` method and the name of this method is still horrible.

**Comment by yevhen** [comment]
> You can try to run the code and you'll see that the result is different. I'm eagerly starting all the async operations by calling ToList on query expression. So they DO run in parallel:)

Ah, right. Sorry, blind me. I was too focused on semantics (one-by-one) than on impl. Nightlife effects :smile: 

> Name of this pattern was borrowed from the Pluralsight cource on async and parallel programming. The original name was wait tasks one-by-one. And I don't think it is misleading, because the name suggests that this code should "process" tasks results one by one, and that is exactly what is happening.

What course? That's really a bad and misleading name. For all my life I was thinking about one-by-one processing as being `in-order` processing and I think it is a universal meaning. It implies that you process results in the original order, which is not the case with your code.

> So if you have better name for this idiom, I would glad to change the name.

Why not just preserving original `WhenAny` name including original method comments with the slight amendment and call it a day?. Original combinator method returns `Task` and yours will return `IEnumerable<Task>`. Also, for performance reasons I would probably provide a first version with a lambda as well.

P.S. I don't watch Pluralsight. Found it to be too boring and spurious :smiley:

**Comment by SergeyTeplyakov** [comment]
> Why not just preserving original WhenAny name including original method comments with the slight amendment and call it a day?

`WhenAny` could be confusing as well. I'm thinking about `OrderByCompletion` or something similar.

> Also, for performance reasons I would probably provide a first version with a lambda as well.

Didn't get why lambda-based version would be much better from performance perspective. I think that overhead for task itself and for async/await stuff should be much more significant that an overhead for an iterator block.

**Comment by yevhen** [comment]
> Didn't get why lambda-based version would be much better from performance perspective. I think that overhead for task itself and for async/await stuff should be much more significant that an overhead for an iterator block.

You're right. We're both making an assumptions about things we haven't measured before :smile: 

> WhenAny could be confusing as well. I'm thinking about OrderByCompletion or something similar.

WhenAny could be a better name for a lambda-based version. For enumerable - I have no idea what name would be a good fit :grinning:

**Comment by SergeyTeplyakov** [comment]
Started with `OrderByCompletion`. Not the best one but should be clear what it does.

**Pull request closed without merging**
